import Head from 'next/head'
import { styled } from '../styles'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ignite Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main >
       
      </main>
    </>
  )
}
